# Generated by Django 4.0.6 on 2022-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_wolof', models.TextField()),
                ('sentence_fr', models.TextField()),
                ('sentence_en', models.TextField()),
            ],
        ),
    ]
